
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - net1
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "433:433"

volumes:
  mariadb_data:

networks:
  net1: